name: MX
version: '5.2 (Fusion)'
api-version: '1.13'
authors: [pawsashatoy, Skr4tch]
description: "Complex combat/automation analysis anti-cheat"
main: kireiko.dev.anticheat.MX
depend: [ ProtocolLib ]
commands:
  mx:
    description: "Main command"
    usage: "/mx"
    permission: "mx.admin"
    aliases: [ mx ]
